### ISSUE TITLE
Legal information / Analytics

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-docs#141]
Does the https://titaniumsdk.com/ need some legal information like Privacy Policy or Terms of Service?
And it looks like it is using Google Analytics. That should only be included when the user accepts it (GDPR, DSGVO) so we might need a cookie banner (or remove it)

**Comment by ewanharris** [comment]
It looks like @cb1kenobi added the GA plugin in [this commit](https://github.com/tidev/titanium-docs/commit/a5cb443d074a99687a2be51fcb74f7a5a960d0a0) so I think he's best to answer how this is configured on the Google side (i.e is [IP masking](https://support.google.com/analytics/answer/2763052?hl=en) enabled) and what might need doing regarding opt-in/opt-out.

I guess one question is has anyone looked at that analytics data since it was added? If not, why keep it?

**Comment by cb1kenobi** [comment]
Yeah, I added it, but I never got it configured correctly:

![image](https://user-images.githubusercontent.com/97262/184995551-f4e6f924-e47b-4e48-bcdb-455ce1a8a429.png)

I'm fine with removing it. However, I do see value in getting it working even if that means we need to add a cookie acceptance popup.
